module.exports.testData = [
  {
    name: 'Simple array',
    in: [
      { name: 'John Doe', age: 18 },
      { name: 'John Smith', age: 18 },
      { name: 'Jane Smith', age: 18 },
    ],
  },
  {
    name: 'players/id/tournaments',
    in: {
      tournaments: [
        {
          extraPoints: { Jogos: '9§0§', Participação: '3§20§' },
          id: 35,
          phases: [
            {
              groupName: 'A',
              phase: 1,
              clubId: 3,
              matches: [
                {
                  id: 1,
                  numFrames: 5,
                  details: null,
                  eta: '2025-03-29T12:00:00.000Z',
                  tableNo: 1,
                  clubId: 3,
                  startedAt: '2025-03-29T12:03:38.000Z',
                  endedAt: '2025-03-29T13:04:43.000Z',
                  players: [
                    { pk: 12973, id: 111, wins: 3, wo: false, points: 3 },
                    { pk: 12972, id: 330, wins: 0, wo: false, points: 0 },
                  ],
                  referee: { pk: 12974, id: null, wo: false },
                },
                {
                  id: 3,
                  numFrames: 5,
                  details: { winner: { bonus: 3, groupPos: 1 } },
                  eta: '2025-03-29T12:00:00.000Z',
                  tableNo: 1,
                  clubId: 3,
                  startedAt: '2025-03-29T13:05:06.000Z',
                  endedAt: '2025-03-29T14:37:25.000Z',
                  players: [
                    {
                      pk: 12978,
                      id: 111,
                      wins: 1,
                      wo: false,
                      sourceMatchId: 1,
                      sourceMatchWho: 'winner',
                      points: 1,
                    },
                    {
                      pk: 12979,
                      id: 115,
                      wins: 3,
                      wo: false,
                      sourceMatchId: 2,
                      sourceMatchWho: 'winner',
                      points: 6,
                    },
                  ],
                  referee: {
                    pk: 12980,
                    id: 262,
                    wo: false,
                    sourceMatchId: 2,
                    sourceMatchWho: 'loser',
                  },
                },
                {
                  id: 5,
                  numFrames: 5,
                  details: { winner: { groupPos: 2 } },
                  eta: '2025-03-29T12:00:00.000Z',
                  tableNo: 1,
                  clubId: 3,
                  startedAt: '2025-03-29T14:59:10.000Z',
                  endedAt: '2025-03-29T15:50:29.000Z',
                  players: [
                    {
                      pk: 12984,
                      id: 111,
                      wins: 3,
                      wo: false,
                      sourceMatchId: 3,
                      sourceMatchWho: 'loser',
                      points: 3,
                    },
                    {
                      pk: 12985,
                      id: 330,
                      wins: 0,
                      wo: false,
                      sourceMatchId: 4,
                      sourceMatchWho: 'winner',
                      points: 0,
                    },
                  ],
                  referee: {
                    pk: 12986,
                    id: 262,
                    wo: false,
                    sourceMatchId: 4,
                    sourceMatchWho: 'loser',
                  },
                },
              ],
            },
            {
              groupName: 'OITAVAS',
              phase: 3,
              clubId: 3,
              matches: [
                {
                  id: 54,
                  numFrames: 5,
                  details: { winner: { bonus: 2 } },
                  eta: null,
                  tableNo: null,
                  clubId: 3,
                  startedAt: '2025-03-29T18:01:38.000Z',
                  endedAt: '2025-03-29T20:03:37.000Z',
                  players: [
                    {
                      pk: 13123,
                      id: 111,
                      wins: 2,
                      wo: false,
                      sourceMatchId: 5,
                      sourceMatchWho: 'winner',
                      points: 2,
                    },
                    {
                      pk: 13124,
                      id: 116,
                      wins: 3,
                      wo: false,
                      sourceMatchId: 23,
                      sourceMatchWho: 'winner',
                      points: 5,
                    },
                  ],
                  referee: { pk: null, id: null, wo: null },
                },
              ],
            },
          ],
        },
      ],
    },
  },
  {
    name: 'tournaments/id/players',
    in: {
      rows: [
        {
          tournamentId: 38,
          playerId: 111,
          createdAt: '2025-04-03T14:29:46.286Z',
        },
        {
          tournamentId: 38,
          playerId: 262,
          createdAt: '2025-04-04T17:29:29.472Z',
        },
        {
          tournamentId: 37,
          playerId: 15,
          createdAt: '2025-04-04T17:29:43.095Z',
        },
        {
          tournamentId: 38,
          playerId: 21,
          createdAt: '2025-04-04T17:30:04.695Z',
        },
        {
          tournamentId: 37,
          playerId: 77,
          createdAt: '2025-04-04T17:30:50.076Z',
        },
        {
          tournamentId: 38,
          playerId: 275,
          createdAt: '2025-04-04T17:32:24.081Z',
        },
        {
          tournamentId: 38,
          playerId: 414,
          createdAt: '2025-04-04T17:33:19.122Z',
        },
        {
          tournamentId: 38,
          playerId: 267,
          createdAt: '2025-04-04T17:36:26.493Z',
        },
        {
          tournamentId: 38,
          playerId: 260,
          createdAt: '2025-04-04T17:45:07.497Z',
        },
        {
          tournamentId: 37,
          playerId: 58,
          createdAt: '2025-04-04T17:45:27.676Z',
        },
        {
          tournamentId: 38,
          playerId: 226,
          createdAt: '2025-04-04T17:59:27.182Z',
        },
        {
          tournamentId: 38,
          playerId: 397,
          createdAt: '2025-04-04T18:07:37.136Z',
        },
        {
          tournamentId: 37,
          playerId: 101,
          createdAt: '2025-04-04T18:20:52.113Z',
        },
        {
          tournamentId: 38,
          playerId: 24,
          createdAt: '2025-04-04T18:22:22.254Z',
        },
        {
          tournamentId: 37,
          playerId: 69,
          createdAt: '2025-04-04T18:27:44.746Z',
        },
        {
          tournamentId: 38,
          playerId: 330,
          createdAt: '2025-04-04T18:30:36.329Z',
        },
        {
          tournamentId: 38,
          playerId: 412,
          createdAt: '2025-04-04T19:26:22.304Z',
        },
        {
          tournamentId: 37,
          playerId: 221,
          createdAt: '2025-04-04T20:10:41.953Z',
        },
        {
          tournamentId: 37,
          playerId: 270,
          createdAt: '2025-04-05T00:23:48.285Z',
        },
        {
          tournamentId: 38,
          playerId: 116,
          createdAt: '2025-04-05T00:27:01.903Z',
        },
        {
          tournamentId: 37,
          playerId: 25,
          createdAt: '2025-04-05T09:21:55.739Z',
        },
        {
          tournamentId: 38,
          playerId: 334,
          createdAt: '2025-04-05T12:00:40.912Z',
        },
        {
          tournamentId: 37,
          playerId: 259,
          createdAt: '2025-04-06T13:22:39.810Z',
        },
        {
          tournamentId: 38,
          playerId: 55,
          createdAt: '2025-04-06T14:26:50.207Z',
        },
      ],
    },
  },
  {
    name: 'v_players',
    in: {
      rows: [
        {
          id: 212,
          name: 'Rafael (SC)',
          categoryId: 3,
          alias: 'Rafael (SC)',
          clubId: null,
          cityId: 23,
          status: 'inactive',
          imgId: 208,
          suspended: null,
          isVirtual: false,
        },
        {
          id: 421,
          name: 'Paulo Roberto Volpe ',
          categoryId: 2,
          alias: 'Tuta',
          clubId: 30,
          cityId: 18,
          status: 'active',
          imgId: 339,
          suspended: null,
          isVirtual: false,
        },
        {
          id: 282,
          name: 'Alex Sandro Fernando Do Prado ',
          categoryId: 2,
          alias: 'Coco',
          clubId: 27,
          cityId: 10,
          status: 'active',
          imgId: 307,
          suspended: null,
          isVirtual: false,
        },
        {
          id: 412,
          name: 'Uidas Almeida De Oliveira ',
          categoryId: 2,
          alias: 'Uidas ',
          clubId: 2,
          cityId: 4,
          status: 'active',
          imgId: 322,
          suspended: null,
          isVirtual: false,
        },
        {
          id: 293,
          name: 'Aparecido Jose Di Santo',
          categoryId: 1,
          alias: 'Zé Do Dito',
          clubId: 7,
          cityId: 36,
          status: 'active',
          imgId: 297,
          suspended: null,
          isVirtual: false,
        },
        {
          id: 330,
          name: 'Mario Dalfre Junior',
          categoryId: 2,
          alias: 'Dalfre ',
          clubId: 26,
          cityId: 14,
          status: 'active',
          imgId: 324,
          suspended: null,
          isVirtual: false,
        },
        {
          id: 334,
          name: 'Diego Ramos Valerio',
          categoryId: 2,
          alias: 'Ramos',
          clubId: 17,
          cityId: 37,
          status: 'active',
          imgId: 306,
          suspended: null,
          isVirtual: false,
        },
        {
          id: 471,
          name: 'Kellerman Jurasseche',
          categoryId: 3,
          alias: 'Magrao',
          clubId: null,
          cityId: 38,
          status: 'active',
          imgId: 329,
          suspended: '',
          isVirtual: false,
        },
        {
          id: 63,
          name: 'Rodrigo Marchiori Mazak ',
          categoryId: 2,
          alias: 'Mazak',
          clubId: 26,
          cityId: 23,
          status: 'active',
          imgId: 249,
          suspended: null,
          isVirtual: false,
        },
        {
          id: 207,
          name: 'Marco (SC)',
          categoryId: 3,
          alias: 'Marco (SC)',
          clubId: null,
          cityId: 23,
          status: 'inactive',
          imgId: 0,
          suspended: null,
          isVirtual: false,
        },
      ],
    },
  },
  {
    name: 'tournaments/i/matches',
    in: {
      tournaments: [
        {
          winners: [],
          id: 38,
          phases: [
            {
              groupName: 'A',
              phase: 1,
              clubId: 20,
              matches: [
                {
                  id: 1,
                  numFrames: 5,
                  details: null,
                  eta: '2025-04-26T12:00:00.000Z',
                  tableNo: 1,
                  clubId: 20,
                  startedAt: null,
                  endedAt: null,
                  players: [
                    { pk: 14499, id: 412, wins: 0, wo: false, points: 0 },
                    { pk: 14500, id: 334, wins: 0, wo: false, points: 0 },
                  ],
                  referee: { pk: 14501, id: 21, wo: false },
                },
                {
                  id: 2,
                  numFrames: 5,
                  details: null,
                  eta: '2025-04-26T12:00:00.000Z',
                  tableNo: 1,
                  clubId: 20,
                  startedAt: null,
                  endedAt: null,
                  players: [
                    { pk: 14502, id: 21, wins: 0, wo: false, points: 0 },
                    { pk: 14503, id: 111, wins: 0, wo: false, points: 0 },
                  ],
                  referee: {
                    pk: 14504,
                    id: null,
                    wo: false,
                    sourceMatchId: 1,
                    sourceMatchWho: 'loser',
                  },
                },
                {
                  id: 3,
                  numFrames: 5,
                  details: { winner: { bonus: 3, groupPos: 1 } },
                  eta: '2025-04-26T12:00:00.000Z',
                  tableNo: 1,
                  clubId: 20,
                  startedAt: null,
                  endedAt: null,
                  players: [
                    {
                      pk: 14505,
                      id: null,
                      wins: 0,
                      wo: false,
                      sourceMatchId: 1,
                      sourceMatchWho: 'winner',
                      points: 0,
                    },
                    {
                      pk: 14506,
                      id: null,
                      wins: 0,
                      wo: false,
                      sourceMatchId: 2,
                      sourceMatchWho: 'winner',
                      points: 0,
                    },
                  ],
                  referee: {
                    pk: 14507,
                    id: null,
                    wo: false,
                    sourceMatchId: 2,
                    sourceMatchWho: 'loser',
                  },
                },
                {
                  id: 4,
                  numFrames: 5,
                  details: null,
                  eta: '2025-04-26T12:00:00.000Z',
                  tableNo: 1,
                  clubId: 20,
                  startedAt: null,
                  endedAt: null,
                  players: [
                    {
                      pk: 14508,
                      id: null,
                      wins: 0,
                      wo: false,
                      sourceMatchId: 1,
                      sourceMatchWho: 'loser',
                      points: 0,
                    },
                    {
                      pk: 14509,
                      id: null,
                      wins: 0,
                      wo: false,
                      sourceMatchId: 2,
                      sourceMatchWho: 'loser',
                      points: 0,
                    },
                  ],
                  referee: {
                    pk: 14510,
                    id: null,
                    wo: false,
                    sourceMatchId: 3,
                    sourceMatchWho: 'winner',
                  },
                },
                {
                  id: 5,
                  numFrames: 5,
                  details: { winner: { groupPos: 2 } },
                  eta: '2025-04-26T12:00:00.000Z',
                  tableNo: 1,
                  clubId: 20,
                  startedAt: null,
                  endedAt: null,
                  players: [
                    {
                      pk: 14511,
                      id: null,
                      wins: 0,
                      wo: false,
                      sourceMatchId: 3,
                      sourceMatchWho: 'loser',
                      points: 0,
                    },
                    {
                      pk: 14512,
                      id: null,
                      wins: 0,
                      wo: false,
                      sourceMatchId: 4,
                      sourceMatchWho: 'winner',
                      points: 0,
                    },
                  ],
                  referee: {
                    pk: 14513,
                    id: null,
                    wo: false,
                    sourceMatchId: 4,
                    sourceMatchWho: 'loser',
                  },
                },
              ],
            },
            {
              groupName: 'B',
              phase: 1,
              clubId: 20,
              matches: [
                {
                  id: 6,
                  numFrames: 5,
                  details: null,
                  eta: '2025-04-26T12:00:00.000Z',
                  tableNo: 2,
                  clubId: 20,
                  startedAt: null,
                  endedAt: null,
                  players: [
                    { pk: 14514, id: 330, wins: 0, wo: false, points: 0 },
                    { pk: 14515, id: 55, wins: 0, wo: false, points: 0 },
                  ],
                  referee: { pk: 14516, id: 226, wo: false },
                },
                {
                  id: 7,
                  numFrames: 5,
                  details: null,
                  eta: '2025-04-26T12:00:00.000Z',
                  tableNo: 2,
                  clubId: 20,
                  startedAt: null,
                  endedAt: null,
                  players: [
                    { pk: 14517, id: 226, wins: 0, wo: false, points: 0 },
                    { pk: 14518, id: 414, wins: 0, wo: false, points: 0 },
                  ],
                  referee: {
                    pk: 14519,
                    id: null,
                    wo: false,
                    sourceMatchId: 6,
                    sourceMatchWho: 'loser',
                  },
                },
                {
                  id: 8,
                  numFrames: 5,
                  details: { winner: { bonus: 3, groupPos: 1 } },
                  eta: '2025-04-26T12:00:00.000Z',
                  tableNo: 2,
                  clubId: 20,
                  startedAt: null,
                  endedAt: null,
                  players: [
                    {
                      pk: 14520,
                      id: null,
                      wins: 0,
                      wo: false,
                      sourceMatchId: 6,
                      sourceMatchWho: 'winner',
                      points: 0,
                    },
                    {
                      pk: 14521,
                      id: null,
                      wins: 0,
                      wo: false,
                      sourceMatchId: 7,
                      sourceMatchWho: 'winner',
                      points: 0,
                    },
                  ],
                  referee: {
                    pk: 14522,
                    id: null,
                    wo: false,
                    sourceMatchId: 7,
                    sourceMatchWho: 'loser',
                  },
                },
                {
                  id: 9,
                  numFrames: 5,
                  details: null,
                  eta: '2025-04-26T12:00:00.000Z',
                  tableNo: 2,
                  clubId: 20,
                  startedAt: null,
                  endedAt: null,
                  players: [
                    {
                      pk: 14523,
                      id: null,
                      wins: 0,
                      wo: false,
                      sourceMatchId: 6,
                      sourceMatchWho: 'loser',
                      points: 0,
                    },
                    {
                      pk: 14524,
                      id: null,
                      wins: 0,
                      wo: false,
                      sourceMatchId: 7,
                      sourceMatchWho: 'loser',
                      points: 0,
                    },
                  ],
                  referee: {
                    pk: 14525,
                    id: null,
                    wo: false,
                    sourceMatchId: 8,
                    sourceMatchWho: 'winner',
                  },
                },
                {
                  id: 10,
                  numFrames: 5,
                  details: { winner: { groupPos: 2 } },
                  eta: '2025-04-26T12:00:00.000Z',
                  tableNo: 2,
                  clubId: 20,
                  startedAt: null,
                  endedAt: null,
                  players: [
                    {
                      pk: 14526,
                      id: null,
                      wins: 0,
                      wo: false,
                      sourceMatchId: 8,
                      sourceMatchWho: 'loser',
                      points: 0,
                    },
                    {
                      pk: 14527,
                      id: null,
                      wins: 0,
                      wo: false,
                      sourceMatchId: 9,
                      sourceMatchWho: 'winner',
                      points: 0,
                    },
                  ],
                  referee: {
                    pk: 14528,
                    id: null,
                    wo: false,
                    sourceMatchId: 9,
                    sourceMatchWho: 'loser',
                  },
                },
              ],
            },
            {
              groupName: 'C',
              phase: 1,
              clubId: 26,
              matches: [
                {
                  id: 11,
                  numFrames: 5,
                  details: null,
                  eta: '2025-04-26T12:00:00.000Z',
                  tableNo: 3,
                  clubId: 26,
                  startedAt: null,
                  endedAt: null,
                  players: [
                    { pk: 14529, id: 116, wins: 0, wo: false, points: 0 },
                    { pk: 14530, id: 24, wins: 0, wo: false, points: 0 },
                  ],
                  referee: { pk: 14531, id: 262, wo: false },
                },
                {
                  id: 12,
                  numFrames: 5,
                  details: null,
                  eta: '2025-04-26T12:00:00.000Z',
                  tableNo: 3,
                  clubId: 26,
                  startedAt: null,
                  endedAt: null,
                  players: [
                    { pk: 14532, id: 262, wins: 0, wo: false, points: 0 },
                    { pk: 14533, id: 267, wins: 0, wo: false, points: 0 },
                  ],
                  referee: {
                    pk: 14534,
                    id: null,
                    wo: false,
                    sourceMatchId: 11,
                    sourceMatchWho: 'loser',
                  },
                },
                {
                  id: 13,
                  numFrames: 5,
                  details: { winner: { bonus: 3, groupPos: 1 } },
                  eta: '2025-04-26T12:00:00.000Z',
                  tableNo: 3,
                  clubId: 26,
                  startedAt: null,
                  endedAt: null,
                  players: [
                    {
                      pk: 14535,
                      id: null,
                      wins: 0,
                      wo: false,
                      sourceMatchId: 11,
                      sourceMatchWho: 'winner',
                      points: 0,
                    },
                    {
                      pk: 14536,
                      id: null,
                      wins: 0,
                      wo: false,
                      sourceMatchId: 12,
                      sourceMatchWho: 'winner',
                      points: 0,
                    },
                  ],
                  referee: {
                    pk: 14537,
                    id: null,
                    wo: false,
                    sourceMatchId: 12,
                    sourceMatchWho: 'loser',
                  },
                },
                {
                  id: 14,
                  numFrames: 5,
                  details: null,
                  eta: '2025-04-26T12:00:00.000Z',
                  tableNo: 3,
                  clubId: 26,
                  startedAt: null,
                  endedAt: null,
                  players: [
                    {
                      pk: 14538,
                      id: null,
                      wins: 0,
                      wo: false,
                      sourceMatchId: 11,
                      sourceMatchWho: 'loser',
                      points: 0,
                    },
                    {
                      pk: 14539,
                      id: null,
                      wins: 0,
                      wo: false,
                      sourceMatchId: 12,
                      sourceMatchWho: 'loser',
                      points: 0,
                    },
                  ],
                  referee: {
                    pk: 14540,
                    id: null,
                    wo: false,
                    sourceMatchId: 13,
                    sourceMatchWho: 'winner',
                  },
                },
                {
                  id: 15,
                  numFrames: 5,
                  details: { winner: { groupPos: 2 } },
                  eta: '2025-04-26T12:00:00.000Z',
                  tableNo: 3,
                  clubId: 26,
                  startedAt: null,
                  endedAt: null,
                  players: [
                    {
                      pk: 14541,
                      id: null,
                      wins: 0,
                      wo: false,
                      sourceMatchId: 13,
                      sourceMatchWho: 'loser',
                      points: 0,
                    },
                    {
                      pk: 14542,
                      id: null,
                      wins: 0,
                      wo: false,
                      sourceMatchId: 14,
                      sourceMatchWho: 'winner',
                      points: 0,
                    },
                  ],
                  referee: {
                    pk: 14543,
                    id: null,
                    wo: false,
                    sourceMatchId: 14,
                    sourceMatchWho: 'loser',
                  },
                },
              ],
            },
            {
              groupName: 'D',
              phase: 1,
              clubId: 26,
              matches: [
                {
                  id: 16,
                  numFrames: 5,
                  details: null,
                  eta: '2025-04-26T12:00:00.000Z',
                  tableNo: 4,
                  clubId: 26,
                  startedAt: null,
                  endedAt: null,
                  players: [
                    { pk: 14544, id: 260, wins: 0, wo: false, points: 0 },
                    { pk: 14545, id: 397, wins: 0, wo: false, points: 0 },
                  ],
                  referee: { pk: 14546, id: 275, wo: false },
                },
                {
                  id: 17,
                  numFrames: 5,
                  details: null,
                  eta: '2025-04-26T12:00:00.000Z',
                  tableNo: 4,
                  clubId: 26,
                  startedAt: null,
                  endedAt: null,
                  players: [
                    { pk: 14547, id: 275, wins: 0, wo: false, points: 0 },
                    { pk: 14548, id: null, wins: 0, wo: false, points: 0 },
                  ],
                  referee: {
                    pk: 14549,
                    id: null,
                    wo: false,
                    sourceMatchId: 16,
                    sourceMatchWho: 'loser',
                  },
                },
                {
                  id: 18,
                  numFrames: 5,
                  details: { winner: { bonus: 3, groupPos: 1 } },
                  eta: '2025-04-26T12:00:00.000Z',
                  tableNo: 4,
                  clubId: 26,
                  startedAt: null,
                  endedAt: null,
                  players: [
                    {
                      pk: 14550,
                      id: null,
                      wins: 0,
                      wo: false,
                      sourceMatchId: 16,
                      sourceMatchWho: 'winner',
                      points: 0,
                    },
                    {
                      pk: 14551,
                      id: null,
                      wins: 0,
                      wo: false,
                      sourceMatchId: 17,
                      sourceMatchWho: 'winner',
                      points: 0,
                    },
                  ],
                  referee: {
                    pk: 14552,
                    id: null,
                    wo: false,
                    sourceMatchId: 17,
                    sourceMatchWho: 'loser',
                  },
                },
                {
                  id: 19,
                  numFrames: 5,
                  details: null,
                  eta: '2025-04-26T12:00:00.000Z',
                  tableNo: 4,
                  clubId: 26,
                  startedAt: null,
                  endedAt: null,
                  players: [
                    {
                      pk: 14553,
                      id: null,
                      wins: 0,
                      wo: false,
                      sourceMatchId: 16,
                      sourceMatchWho: 'loser',
                      points: 0,
                    },
                    {
                      pk: 14554,
                      id: null,
                      wins: 0,
                      wo: false,
                      sourceMatchId: 17,
                      sourceMatchWho: 'loser',
                      points: 0,
                    },
                  ],
                  referee: {
                    pk: 14555,
                    id: null,
                    wo: false,
                    sourceMatchId: 18,
                    sourceMatchWho: 'winner',
                  },
                },
                {
                  id: 20,
                  numFrames: 5,
                  details: { winner: { groupPos: 2 } },
                  eta: '2025-04-26T12:00:00.000Z',
                  tableNo: 4,
                  clubId: 26,
                  startedAt: null,
                  endedAt: null,
                  players: [
                    {
                      pk: 14556,
                      id: null,
                      wins: 0,
                      wo: false,
                      sourceMatchId: 18,
                      sourceMatchWho: 'loser',
                      points: 0,
                    },
                    {
                      pk: 14557,
                      id: null,
                      wins: 0,
                      wo: false,
                      sourceMatchId: 19,
                      sourceMatchWho: 'winner',
                      points: 0,
                    },
                  ],
                  referee: {
                    pk: 14558,
                    id: null,
                    wo: false,
                    sourceMatchId: 19,
                    sourceMatchWho: 'loser',
                  },
                },
              ],
            },
            {
              groupName: 'QUARTAS',
              phase: 2,
              clubId: 20,
              matches: [
                {
                  id: 21,
                  numFrames: 5,
                  details: { winner: { bonus: 2 } },
                  eta: null,
                  tableNo: null,
                  clubId: 20,
                  startedAt: null,
                  endedAt: null,
                  players: [
                    {
                      pk: 14559,
                      id: null,
                      wins: 0,
                      wo: false,
                      sourceMatchId: 8,
                      sourceMatchWho: 'winner',
                      points: 0,
                    },
                    {
                      pk: 14560,
                      id: null,
                      wins: 0,
                      wo: false,
                      sourceMatchId: 20,
                      sourceMatchWho: 'winner',
                      points: 0,
                    },
                  ],
                  referee: { pk: null, id: null, wo: null },
                },
                {
                  id: 22,
                  numFrames: 5,
                  details: { winner: { bonus: 2 } },
                  eta: null,
                  tableNo: null,
                  clubId: 20,
                  startedAt: null,
                  endedAt: null,
                  players: [
                    {
                      pk: 14561,
                      id: null,
                      wins: 0,
                      wo: false,
                      sourceMatchId: 18,
                      sourceMatchWho: 'winner',
                      points: 0,
                    },
                    {
                      pk: 14562,
                      id: null,
                      wins: 0,
                      wo: false,
                      sourceMatchId: 10,
                      sourceMatchWho: 'winner',
                      points: 0,
                    },
                  ],
                  referee: { pk: null, id: null, wo: null },
                },
                {
                  id: 23,
                  numFrames: 5,
                  details: { winner: { bonus: 2 } },
                  eta: null,
                  tableNo: null,
                  clubId: 20,
                  startedAt: null,
                  endedAt: null,
                  players: [
                    {
                      pk: 14563,
                      id: null,
                      wins: 0,
                      wo: false,
                      sourceMatchId: 3,
                      sourceMatchWho: 'winner',
                      points: 0,
                    },
                    {
                      pk: 14564,
                      id: null,
                      wins: 0,
                      wo: false,
                      sourceMatchId: 15,
                      sourceMatchWho: 'winner',
                      points: 0,
                    },
                  ],
                  referee: { pk: null, id: null, wo: null },
                },
                {
                  id: 24,
                  numFrames: 5,
                  details: { winner: { bonus: 2 } },
                  eta: null,
                  tableNo: null,
                  clubId: 20,
                  startedAt: null,
                  endedAt: null,
                  players: [
                    {
                      pk: 14565,
                      id: null,
                      wins: 0,
                      wo: false,
                      sourceMatchId: 13,
                      sourceMatchWho: 'winner',
                      points: 0,
                    },
                    {
                      pk: 14566,
                      id: null,
                      wins: 0,
                      wo: false,
                      sourceMatchId: 5,
                      sourceMatchWho: 'winner',
                      points: 0,
                    },
                  ],
                  referee: { pk: null, id: null, wo: null },
                },
              ],
            },
            {
              groupName: 'SEMI-FINAIS',
              phase: 3,
              clubId: 20,
              matches: [
                {
                  id: 25,
                  numFrames: 5,
                  details: { winner: { bonus: 2 } },
                  eta: null,
                  tableNo: null,
                  clubId: 20,
                  startedAt: null,
                  endedAt: null,
                  players: [
                    {
                      pk: 14567,
                      id: null,
                      wins: 0,
                      wo: false,
                      sourceMatchId: 22,
                      sourceMatchWho: 'winner',
                      points: 0,
                    },
                    {
                      pk: 14568,
                      id: null,
                      wins: 0,
                      wo: false,
                      sourceMatchId: 24,
                      sourceMatchWho: 'winner',
                      points: 0,
                    },
                  ],
                  referee: { pk: null, id: null, wo: null },
                },
                {
                  id: 26,
                  numFrames: 5,
                  details: { winner: { bonus: 2 } },
                  eta: null,
                  tableNo: null,
                  clubId: 20,
                  startedAt: null,
                  endedAt: null,
                  players: [
                    {
                      pk: 14569,
                      id: null,
                      wins: 0,
                      wo: false,
                      sourceMatchId: 21,
                      sourceMatchWho: 'winner',
                      points: 0,
                    },
                    {
                      pk: 14570,
                      id: null,
                      wins: 0,
                      wo: false,
                      sourceMatchId: 23,
                      sourceMatchWho: 'winner',
                      points: 0,
                    },
                  ],
                  referee: { pk: null, id: null, wo: null },
                },
              ],
            },
            {
              groupName: 'FINAL',
              phase: 4,
              clubId: 20,
              matches: [
                {
                  id: 27,
                  numFrames: 5,
                  details: {
                    loser: { finalPos: 2 },
                    winner: { bonus: 3, finalPos: 1 },
                  },
                  eta: null,
                  tableNo: null,
                  clubId: 20,
                  startedAt: null,
                  endedAt: null,
                  players: [
                    {
                      pk: 14571,
                      id: null,
                      wins: 0,
                      wo: false,
                      sourceMatchId: 25,
                      sourceMatchWho: 'winner',
                      points: 0,
                    },
                    {
                      pk: 14572,
                      id: null,
                      wins: 0,
                      wo: false,
                      sourceMatchId: 26,
                      sourceMatchWho: 'winner',
                      points: 0,
                    },
                  ],
                  referee: { pk: null, id: null, wo: null },
                },
              ],
            },
            {
              groupName: 'TERCEIRO',
              phase: 4,
              clubId: 20,
              matches: [
                {
                  id: 28,
                  numFrames: 5,
                  details: {
                    loser: { finalPos: 4 },
                    winner: { bonus: 1, finalPos: 3 },
                  },
                  eta: null,
                  tableNo: null,
                  clubId: 20,
                  startedAt: null,
                  endedAt: null,
                  players: [
                    {
                      pk: 14573,
                      id: null,
                      wins: 0,
                      wo: false,
                      sourceMatchId: 25,
                      sourceMatchWho: 'loser',
                      points: 0,
                    },
                    {
                      pk: 14574,
                      id: null,
                      wins: 0,
                      wo: false,
                      sourceMatchId: 26,
                      sourceMatchWho: 'loser',
                      points: 0,
                    },
                  ],
                  referee: { pk: null, id: null, wo: null },
                },
              ],
            },
          ],
        },
      ],
    },
  },
  {
    name: 'simple-players',
    in: [
      { name: 'Kellerman Jurasseche', alias: 'Magrao', status: 'inactive' },
      { name: 'Rafael (SC)', alias: 'Rafael (SC)', status: 'inactive' },
      {
        name: 'Marcos Roberto Rodrigues ',
        alias: 'Markinhos',
        status: 'inactive',
      },
      { name: 'Davi Flores Gonçalves ', alias: 'Gauchinho ', status: 'active' },
      { name: 'José Carlos Diniz Lima ', alias: 'Diniz ', status: 'active' },
      { name: 'Marco (SC)', alias: 'Marco (SC)', status: 'inactive' },
      { name: 'Edson José de Souza ', alias: 'Edinho', status: 'inactive' },
      {
        name: 'Roberto Augusto De Campos',
        alias: 'Beto Campo',
        status: 'inactive',
      },
      { name: 'Rodrigo Marchiori Mazak ', alias: 'Mazak', status: 'inactive' },
      { name: 'Estevam Viragh Junior', alias: 'Estevam', status: 'active' },
      { name: 'Evandro', alias: 'Evandro', status: 'inactive' },
      {
        name: 'Uidas Almeida De Oliveira ',
        alias: 'Uidas ',
        status: 'inactive',
      },
      {
        name: 'André Oscar Ferreira Arantes',
        alias: 'Andreoscar',
        status: 'inactive',
      },
      { name: 'Mario Quiudini Junior', alias: 'Dr Mário', status: 'inactive' },
      {
        name: 'Alex Sandro Fernando Do Prado ',
        alias: 'Coco',
        status: 'active',
      },
      { name: 'Marcelo Carminatti ', alias: 'Marcelinho', status: 'active' },
      {
        name: 'Paulo Cesar Betarelle ',
        alias: 'Betarelle ',
        status: 'inactive',
      },
      { name: 'Paulo Roberto Volpe ', alias: 'Tuta', status: 'active' },
      { name: 'Raphael Mairal', alias: 'Mairal', status: 'active' },
      {
        name: 'Reginaldo Henrique Barbosa  ',
        alias: 'Regis',
        status: 'active',
      },
      { name: 'Braga (SC)', alias: 'Braga (SC)', status: 'inactive' },
      { name: 'Laercio Jorge Souza', alias: 'Laercio', status: 'inactive' },
      {
        name: 'Patricia Aparecida Bencardini',
        alias: 'Paty',
        status: 'inactive',
      },
      { name: 'Lucas Saturnino', alias: 'Jhow', status: 'active' },
      {
        name: 'João Henrique Zerunian ',
        alias: 'Jhzerunian',
        status: 'active',
      },
      {
        name: 'Edílson de Oliveira Prado ',
        alias: 'Edílson',
        status: 'active',
      },
      {
        name: 'Mauricio (Vinhedo)',
        alias: 'Mauricio (Vinhedo)',
        status: 'inactive',
      },
      { name: 'Valtinho (SC)', alias: 'Valtinho (SC)', status: 'inactive' },
      { name: 'Juninho (SC)', alias: 'Juninho (SC)', status: 'inactive' },
      { name: 'Wanderez Bueno de Assis', alias: 'Bueno', status: 'active' },
      { name: 'Sergio Ossamu Hamano', alias: 'Serginho', status: 'inactive' },
      { name: 'Ronaldo Pinfildi ', alias: 'Ronaldo', status: 'active' },
      {
        name: 'Rafael Ribeiro Urano Alves ',
        alias: 'Rafinha',
        status: 'inactive',
      },
      { name: 'Gustavo Eduardo Luaces', alias: 'Argentino', status: 'active' },
      { name: 'Rivanil José Paiva ', alias: 'Riva', status: 'active' },
      { name: 'Maciel Gama', alias: 'Maciel', status: 'inactive' },
      {
        name: 'Rhariel Seda Jurasseche Prado Lima',
        alias: 'Rhariel',
        status: 'inactive',
      },
      { name: 'Mario Dalfre Junior', alias: 'Dalfre ', status: 'active' },
      { name: 'Fabio de Sousa Vieira', alias: 'Vieira', status: 'inactive' },
      { name: 'Luiz Braga De Assis ', alias: 'Braga Boys', status: 'inactive' },
      { name: 'Wilson Roberto Roque', alias: 'Gordinho S', status: 'active' },
      { name: 'Luciano Pestiglio', alias: 'Luciano ', status: 'inactive' },
      { name: 'Miguel Rodrigues Amancio', alias: 'Miguel', status: 'inactive' },
      { name: 'Paulo Roberto Volpe ', alias: 'Tuta Ext', status: 'inactive' },
      { name: 'Marcelo Francisco Idalgo', alias: 'Paçoca', status: 'active' },
      { name: 'Denis Eustáquio Borges', alias: 'Denis Sj', status: 'inactive' },
      { name: 'Sidmar Oliveira Dias ', alias: 'Sidmar', status: 'active' },
      {
        name: 'Luis Carlos Bortoleto Da Silva',
        alias: 'Bilú',
        status: 'active',
      },
      { name: 'Adão Edson Caraça ', alias: 'EdsonSC', status: 'active' },
      { name: 'Marcelo Costa Leite', alias: 'Marcelo', status: 'inactive' },
      {
        name: 'Kauê Aruanã Teixeira Leite',
        alias: 'Kauê Leite',
        status: 'inactive',
      },
      { name: 'Victor Vieira', alias: 'Victor', status: 'inactive' },
      {
        name: 'Rafael Gomes Medeiro ',
        alias: 'Rafa Gomes',
        status: 'inactive',
      },
      {
        name: 'Cleber Odenir Rodrigues Gonçalves',
        alias: 'Gaúcho ',
        status: 'active',
      },
      { name: 'Arthur Bergamo Volpe ', alias: 'Volpe', status: 'active' },
      { name: 'Andre De Souza ', alias: 'André ', status: 'active' },
      { name: 'Ericles Do Carmo Mariano', alias: 'Mariano', status: 'active' },
      {
        name: 'João Paulo Rocha Alves De Araújo',
        alias: 'João Rocha',
        status: 'active',
      },
      { name: 'ASSISP', alias: 'ASSISP', status: 'active' },
      {
        name: 'Marcelo Carminatti (ext)',
        alias: 'Marcelinho-C',
        status: 'inactive',
      },
      {
        name: 'Evandro Alexandre Marangon ',
        alias: 'Marangon',
        status: 'active',
      },
      { name: 'Nelson Vedroni', alias: 'Nelson-V', status: 'inactive' },
      { name: 'Benê (sjrp)', alias: 'Benê (sjrp)', status: 'inactive' },
      { name: 'Edson Baida ', alias: 'Baida', status: 'active' },
      {
        name: 'Ernandes Sozan Rodrigues De Araújo ',
        alias: 'Nande ',
        status: 'active',
      },
      {
        name: 'Francisco De Salles Dias Junior ',
        alias: 'Chico Sall',
        status: 'inactive',
      },
      { name: 'Arthur Bergamo Volpe ', alias: 'Volpe Ext', status: 'inactive' },
      { name: 'André Natali Amâncio ', alias: 'Belezão', status: 'active' },
      { name: 'Carlos Alberto de Souza ', alias: 'Carlão', status: 'inactive' },
      {
        name: 'Laurentino Gonzales Del Rio ',
        alias: 'Lauro',
        status: 'inactive',
      },
      {
        name: 'Murilo Orpinelli Fonseca',
        alias: 'Mumuzinho',
        status: 'active',
      },
      {
        name: 'Marcelo Roberto Pereira do Nascimento ',
        alias: 'Samuka',
        status: 'active',
      },
      { name: 'Edson Moreira Banhos', alias: 'Banhos', status: 'active' },
      { name: 'Marcos Rodrigues ', alias: 'Tota', status: 'inactive' },
      { name: 'João Capela', alias: 'Capela', status: 'active' },
      { name: 'Victor Otavio Ferretto ', alias: 'Ferretto ', status: 'active' },
      { name: 'Silvio Cesar Vieira', alias: 'Silvio', status: 'active' },
      { name: 'Gilberto Urano Alves', alias: 'Giba', status: 'active' },
      {
        name: 'Geraldo Júnior Amorim Albuquerque',
        alias: 'Amorim',
        status: 'active',
      },
      { name: 'Murilo Ferreira De Araujo ', alias: 'Mumu', status: 'active' },
      {
        name: 'João Baptista Camargo Alves Jr ',
        alias: 'João Jr',
        status: 'active',
      },
      { name: 'Tomas Edson Barros ', alias: 'Tomas', status: 'active' },
      { name: 'Paulo Bueno', alias: 'Paulo', status: 'active' },
      { name: 'Pedro Henrique Roncalho ', alias: 'Roncalho', status: 'active' },
      { name: 'Levi Bulon Guerra', alias: 'Levi', status: 'active' },
      { name: 'Sandro Augusto Israel', alias: 'Sandrinho', status: 'active' },
      { name: 'Heleno de Souza Barbosa ', alias: 'Heleno', status: 'inactive' },
      { name: 'Guilherme Begnami ', alias: 'Guilherme', status: 'active' },
      {
        name: 'Carlos Alberto Pelissari ',
        alias: 'Pelissari',
        status: 'active',
      },
      {
        name: 'Paulo Fernando Bernardo ',
        alias: 'Paulo F',
        status: 'inactive',
      },
      {
        name: 'Sebastião Pereira de Araujo ',
        alias: 'Pereira',
        status: 'inactive',
      },
      { name: 'Natal Messias Ferreira ', alias: 'Natal', status: 'inactive' },
      { name: 'Vinicius Da Silva Fucuta', alias: 'Fucuta', status: 'active' },
      { name: 'Mebel Luiz Jorge', alias: 'Mebel ', status: 'inactive' },
      {
        name: 'Aparecido Jose Di Santo',
        alias: 'Zé Do Dito',
        status: 'active',
      },
      { name: 'Savério Wilson Simoni ', alias: 'Wilson', status: 'inactive' },
      {
        name: 'Marcelo Rodrigues Da Silva ',
        alias: 'Marcel Apv',
        status: 'inactive',
      },
      { name: 'Rogerio Nose', alias: 'Rogerio N', status: 'inactive' },
      { name: 'Laurentino G. Del Rio', alias: 'Laurentino', status: 'active' },
      { name: 'Alvaro Arroyo Sobrinho ', alias: 'Arroyo', status: 'active' },
      { name: 'Fernando Cesar Galina ', alias: 'Galina', status: 'active' },
      {
        name: 'Daniela Varjão De Almeida ',
        alias: 'Danny',
        status: 'inactive',
      },
      { name: 'Bruno Alves Garcia', alias: 'Bruno', status: 'inactive' },
      {
        name: 'Murilo Ferreira de Araújo ',
        alias: 'Murilo',
        status: 'inactive',
      },
      {
        name: 'Vagner Alberto Monteiro ',
        alias: 'Vagnao (ext)',
        status: 'inactive',
      },
      { name: 'Vagner Alberto Monteiro ', alias: 'Vagnao', status: 'active' },
      { name: 'Edson Baida ', alias: 'Baida Ext', status: 'inactive' },
      { name: 'Robson Farias Da Silva', alias: 'Robson', status: 'active' },
      { name: 'Helio Da Costa Breda', alias: 'Helinho ', status: 'inactive' },
      {
        name: 'Fábio Henrique Esprovieri ',
        alias: 'Esprovieri',
        status: 'active',
      },
      { name: 'Wagner Ferreira Martinez', alias: 'Martinez', status: 'active' },
      {
        name: 'Francis Eduardo Campagnollo ',
        alias: 'Francis',
        status: 'active',
      },
      { name: 'Eleandro Carlos Cagnin ', alias: 'Eleandro', status: 'active' },
      { name: 'Nilson Teodósio', alias: 'Nelson', status: 'active' },
      { name: 'Marcelo Novas Pinotti ', alias: 'Marcelão', status: 'active' },
      { name: 'Rafael Aparecido Sória ', alias: 'Sória ', status: 'active' },
      { name: 'Mauro Antonio Teodoro', alias: 'Mauro Ext', status: 'inactive' },
      { name: 'Rogério Leandro Garcia ', alias: 'Rogerão', status: 'active' },
      { name: 'Sandro', alias: 'SandroL', status: 'inactive' },
      { name: 'Emerson Medaglia Furlan', alias: 'Medaglia', status: 'active' },
      { name: 'Romario De Oliveira Lima', alias: 'Romario ', status: 'active' },
      {
        name: 'Willie Reis Da Costa ',
        alias: 'Dville Cos',
        status: 'inactive',
      },
      {
        name: 'José Renilson Dos Santos ',
        alias: 'Zé Santos',
        status: 'inactive',
      },
      { name: 'Ricardo Garcindo Gullo ', alias: 'Ricardo', status: 'active' },
      { name: 'Rodrigo Denardi ', alias: 'Rodrigo', status: 'active' },
      { name: 'Paulo Leme Gonzalez Büll', alias: 'Bull', status: 'active' },
      { name: 'Cristiano Pereira ', alias: 'C P', status: 'active' },
      { name: 'Gilmar Donizete Bordin ', alias: 'Peninha', status: 'active' },
      {
        name: 'Marcos Antonio Cortez Maya ',
        alias: 'Cortez',
        status: 'active',
      },
      { name: 'José Antonio da Silva ', alias: 'Pardal', status: 'active' },
      {
        name: 'Roberto Venâncio Ferreira',
        alias: 'Venâncio ',
        status: 'inactive',
      },
      {
        name: 'Ighor Carvalho De Figueiredo',
        alias: 'Ighor',
        status: 'inactive',
      },
      { name: 'Francisco Almino Uchoa', alias: 'Uchôa', status: 'inactive' },
      {
        name: 'João Pedro Batista Cagnin ',
        alias: 'João Pedro',
        status: 'inactive',
      },
      { name: 'Alexandre Betti Junior ', alias: 'Alex', status: 'inactive' },
      { name: 'Omar Ali Zeitoum', alias: 'Maico', status: 'active' },
      { name: 'Adriano Sgarbi ', alias: 'Palmito ', status: 'inactive' },
      { name: 'Eduardo Oliva Aniceto', alias: 'Garotinho', status: 'inactive' },
      { name: 'Marcel Carrera', alias: 'Marcel', status: 'inactive' },
      { name: 'Diego Ramos Valerio', alias: 'Ramos', status: 'active' },
      { name: 'Juan Wilfredo Pomier Sumi ', alias: 'Juan', status: 'active' },
      { name: 'Rogério Luiz Vasques ', alias: 'Rogério', status: 'active' },
      {
        name: 'Marcos Eli Dos Santos Malmonge ',
        alias: 'Marlboro',
        status: 'active',
      },
      {
        name: 'Mauricio Próspero Chiminazzo',
        alias: 'Primavera',
        status: 'active',
      },
      {
        name: 'Ernesto Carolino Junior',
        alias: 'Nestinho',
        status: 'inactive',
      },
      { name: 'Antônio Moreira Júnior ', alias: 'Juninho', status: 'active' },
      {
        name: 'Jorge Luiz Vieira de Paula ',
        alias: 'Jorjão',
        status: 'active',
      },
      { name: 'Georg Klar ', alias: 'Georg', status: 'active' },
      { name: 'Dr. Aued (Sjrp)', alias: 'Dr Aued (Sjrp)', status: 'inactive' },
      { name: 'Fernando (Cat)', alias: 'Fernando (Cat)', status: 'inactive' },
      { name: 'Francisco Izaias Lyra ', alias: 'Lyra', status: 'inactive' },
      { name: 'Fábio Fer', alias: 'Fábio Fer', status: 'inactive' },
      { name: 'Yan Patrick Giusti ', alias: 'Yan', status: 'inactive' },
      {
        name: 'Marcelo Ferreira Gonzalez ',
        alias: 'Tartaruga',
        status: 'inactive',
      },
      { name: 'Rivanil José Paiva ', alias: 'Rivanil', status: 'inactive' },
      {
        name: 'Adílson Brito dos Santos ',
        alias: 'Adílson',
        status: 'inactive',
      },
      { name: 'n/a', alias: 'n/a', status: 'inactive' },
      { name: 'Marcelo-sjrp', alias: 'Marcelo-sjrp', status: 'inactive' },
      { name: 'Marco Antonio Bianchi', alias: 'Marco', status: 'inactive' },
      { name: 'Luis Eduardo Candiani ', alias: 'Eduardo', status: 'inactive' },
      {
        name: 'Carlos de Giovani Antonio ',
        alias: 'Giovani',
        status: 'inactive',
      },
      {
        name: 'José Roberto Martins Segalla ',
        alias: 'Dr.Segalla',
        status: 'inactive',
      },
      {
        name: 'Rui Carlos Pietronero ',
        alias: 'Rui Gorpeta',
        status: 'in memoriam',
      },
      { name: 'Ovidio Richard Crnkovic ', alias: 'Ovidio', status: 'inactive' },
      {
        name: 'Fernando Silveira Brasil ',
        alias: 'Fernando Brasil',
        status: 'inactive',
      },
      { name: 'Lázaro da Silva Pereira ', alias: 'Lazo', status: 'inactive' },
      { name: 'José Eden Matosinho ', alias: 'Matosinho', status: 'inactive' },
      { name: 'James Herrero ', alias: 'James', status: 'inactive' },
      {
        name: 'Paulo Eduardo Passos ',
        alias: 'Paulinho C.V.',
        status: 'inactive',
      },
      { name: 'Eduardo Macelani Vidal ', alias: 'Alemão', status: 'inactive' },
      {
        name: 'Fernando Gomes da Silva ',
        alias: 'Fernando',
        status: 'inactive',
      },
      { name: 'Rafael Gomes Medeiro ', alias: 'RafaelG', status: 'inactive' },
      { name: 'Ronaldo (Cat)', alias: 'Ronaldo (Cat)', status: 'inactive' },
      { name: 'Betarelli', alias: 'Betarelli', status: 'inactive' },
      { name: 'Pitú', alias: 'Pitú', status: 'inactive' },
      { name: 'Jordão', alias: 'Jordão', status: 'inactive' },
      { name: 'Luizão', alias: 'Luizão', status: 'inactive' },
      { name: 'Omar', alias: 'Omar', status: 'inactive' },
      {
        name: 'João Pedro (Cat)',
        alias: 'João Pedro (Cat)',
        status: 'inactive',
      },
      { name: 'Bilú (Cat)', alias: 'Bilú (Cat)', status: 'inactive' },
      {
        name: 'Ighor Carvalho de Figueiredo ',
        alias: 'Ighor-x',
        status: 'inactive',
      },
      {
        name: 'Ricien Diego Carlino da Costa ',
        alias: 'Diego1',
        status: 'inactive',
      },
      {
        name: 'Francisco Vivaldo Pestiglio ',
        alias: 'Sr. Chico',
        status: 'in memoriam',
      },
      { name: 'José Cacheta ', alias: 'Cacheta', status: 'inactive' },
      { name: 'José Citeli ', alias: 'Zéca', status: 'inactive' },
      { name: 'Vinicius Da Silva Fucuta', alias: 'Renato', status: 'inactive' },
      {
        name: 'Osvaldo Viana da Silva filho ',
        alias: 'Osvaldo',
        status: 'inactive',
      },
      {
        name: 'Luis Fernando de Matos Ruiz ',
        alias: 'Dr. Luis Fernando',
        status: 'in memoriam',
      },
      {
        name: 'José de Andrade Lima Júnior ',
        alias: 'Juquinha',
        status: 'inactive',
      },
      { name: 'Denis Azevedo Nunes ', alias: 'Denis', status: 'inactive' },
      {
        name: 'Erley Brignoli de Medeiros ',
        alias: 'Erley',
        status: 'in memoriam',
      },
      { name: 'José Waldonir Bernardo ', alias: 'Mineiro', status: 'inactive' },
      {
        name: 'José Roberto Leme de Andrade ',
        alias: 'Betão',
        status: 'inactive',
      },
      {
        name: 'Cleber Saladino Pereira ',
        alias: 'Clebinho',
        status: 'inactive',
      },
      {
        name: 'João Alberto Monteiro Filho ',
        alias: 'Joãozinho',
        status: 'inactive',
      },
      {
        name: 'Rodrigo Porrio de Andrade ',
        alias: 'Andrade',
        status: 'inactive',
      },
      { name: 'Alexandre Licioni ', alias: 'Alexandre', status: 'in memoriam' },
      {
        name: 'Alex Sandro Fernando do Prado ',
        alias: 'AlexSandro',
        status: 'inactive',
      },
      {
        name: 'Marcelo Renato Carminatti ',
        alias: 'Marcelo-C',
        status: 'in memoriam',
      },
      {
        name: 'Luiz Carlos Garcia da Silva ',
        alias: 'Padeiro',
        status: 'inactive',
      },
      { name: 'Lourival Moreira', alias: 'Lourival', status: 'inactive' },
      { name: 'Pedro Luiz Poli ', alias: 'Pedro Poli', status: 'inactive' },
      { name: 'Diego Ferraresi Caruzo ', alias: 'Diego-F', status: 'inactive' },
      { name: 'BYE', alias: 'BYE', status: 'active' },
      { name: 'Luciano Pestiglio ', alias: 'Luciano', status: 'inactive' },
      { name: 'João Pedro Freitas Silva ', alias: 'JP', status: 'inactive' },
      { name: 'João Rocha', alias: 'João RochaX', status: 'inactive' },
      {
        name: 'Carlos Roberto da Silva ',
        alias: 'Roberto-SC',
        status: 'inactive',
      },
      {
        name: 'Homero Antônio Ribas ',
        alias: 'Homero Ext',
        status: 'inactive',
      },
      {
        name: 'Kauê Aruanã Teixeira Leite',
        alias: 'Kauê Ext',
        status: 'inactive',
      },
      { name: 'Leandro Chagas De Sena', alias: 'Leco', status: 'inactive' },
      { name: 'Mauro Antonio Teodoro', alias: 'Mauro', status: 'active' },
      { name: 'WO', alias: 'WO', status: 'inactive' },
      { name: 'Marcelo Gagliardi', alias: 'Gaúcho', status: 'active' },
      { name: 'Ronald Carneiro ', alias: 'Ronald', status: 'inactive' },
      {
        name: 'Rogaciano Virgínio Barbosa ',
        alias: 'Luciano-V',
        status: 'inactive',
      },
      {
        name: 'Danilo Massaro de Oliveira ',
        alias: 'Danilo',
        status: 'inactive',
      },
      {
        name: 'Luiz Augusto de Moraes e Silva ',
        alias: 'Luizinho',
        status: 'inactive',
      },
      { name: 'José Gonzaga de Barros ', alias: 'Magrão', status: 'inactive' },
      { name: 'Marcelo Costa Leite', alias: 'Marcelo Ext', status: 'inactive' },
      { name: 'Sérgio de Barros ', alias: 'Sérgio-B', status: 'inactive' },
      { name: 'Mário Yatsunami ', alias: 'Mário', status: 'inactive' },
      {
        name: 'José Carlos Silva Schumacher ',
        alias: 'Zé Preto',
        status: 'inactive',
      },
      { name: 'Rafael Bottino ', alias: 'Botta', status: 'inactive' },
      {
        name: 'Wagner Miguel Rychlicki Elias ',
        alias: 'Wagner',
        status: 'inactive',
      },
      { name: 'Emerson Luis Woigt ', alias: 'Emerson', status: 'inactive' },
      {
        name: 'Anderson Wilson Simoni ',
        alias: 'Anderson',
        status: 'inactive',
      },
      {
        name: 'Alexandre Henrique Crisci ',
        alias: 'Alexandre-H',
        status: 'inactive',
      },
      {
        name: 'Paulo Leme Gonzales Büll ',
        alias: 'Paulo AAA',
        status: 'inactive',
      },
      {
        name: 'Fernando Gonçalves da Silva ',
        alias: 'Panela',
        status: 'inactive',
      },
      {
        name: 'Marcelo Moreira Da Silva',
        alias: 'Marcelo M',
        status: 'inactive',
      },
      {
        name: 'Marcelo Novas Pinotti ',
        alias: 'Marcelo-N',
        status: 'inactive',
      },
      { name: 'Gilson Batista ', alias: 'Gilson', status: 'inactive' },
      { name: 'Marcelo Vaccari ', alias: 'Marcelo-V', status: 'inactive' },
      { name: 'Dênis', alias: 'Dênis', status: 'inactive' },
      { name: 'Tuto', alias: 'Tuto', status: 'inactive' },
      {
        name: 'José Francisco Martins ',
        alias: 'Frank (ext)',
        status: 'inactive',
      },
      {
        name: 'Renato dos Santos (ext)',
        alias: 'Renato-S',
        status: 'inactive',
      },
      { name: 'José Francisco Martins ', alias: 'Frank', status: 'active' },
      {
        name: 'João Milton da Silva Junior ',
        alias: 'Juninho-S',
        status: 'inactive',
      },
      { name: 'Sergio Vieira Lima', alias: 'Sergio Sp', status: 'inactive' },
      {
        name: 'Ricardo Albuquerque Mesquita ',
        alias: 'Ricardão',
        status: 'inactive',
      },
      { name: 'Homero Antônio Ribas ', alias: 'Homero', status: 'active' },
      {
        name: 'Pitágoras Ferreira de Moura ',
        alias: 'Moura',
        status: 'active',
      },
      { name: 'Ailton Andrade dos Santos ', alias: 'Cabeça', status: 'active' },
      {
        name: 'Valter Luiz Alves dos Santos ',
        alias: 'Valtinho',
        status: 'inactive',
      },
      { name: 'Odair Donizeti Fontana', alias: 'Uri', status: 'active' },
      { name: 'José Carlos Damiano ', alias: 'Damiano', status: 'active' },
      { name: 'José Luiz Carossi ', alias: 'Zé Luiz', status: 'active' },
      { name: 'Sérgio Gomes Júnior  ', alias: 'SérgioSom', status: 'active' },
      {
        name: 'Murilo Ferreira de Araújo ',
        alias: 'Murilo-F',
        status: 'inactive',
      },
      { name: 'Diego Souza Ramalho', alias: 'Diego', status: 'inactive' },
      { name: 'Orivaldo Nahes Colombo', alias: 'Colombo', status: 'active' },
      {
        name: 'Maurício Aparecido Gonçalves ',
        alias: 'Dr. Maurício',
        status: 'active',
      },
      { name: 'Eduardo Lourenço Gugliotti ', alias: 'Eddie', status: 'active' },
      { name: 'Leandro José Picinin ', alias: 'Leandro', status: 'active' },
      { name: 'Antonio Carlos Poli ', alias: 'Lico', status: 'active' },
      { name: 'Esau Pereira', alias: 'Esau', status: 'active' },
      { name: 'Gerson Trocatti ', alias: 'Gersinho ', status: 'active' },
      { name: 'Antônio Garcia Júnior ', alias: 'Garcia', status: 'active' },
      {
        name: 'Maurino Carvalho De Campos',
        alias: 'Campos',
        status: 'inactive',
      },
      {
        name: 'José Roberto Tomaz Da Silva',
        alias: 'Roberto',
        status: 'active',
      },
      {
        name: 'Alvaro Arroyo Sobrinho ',
        alias: 'Arroyo Ext',
        status: 'inactive',
      },
      { name: 'Alexandre Ricardo Silva ', alias: 'Spiga', status: 'active' },
      { name: 'Mário Marcenaro Jr. ', alias: 'Marinho', status: 'active' },
      {
        name: 'Fernando Augusto Candia Mendes',
        alias: 'Fernandão ',
        status: 'active',
      },
      { name: 'James Carlos Herrero ', alias: 'James Bond', status: 'active' },
      { name: 'Antônio Carlos Merendino', alias: 'Toninho', status: 'active' },
    ].sort((a, b) => a.name.localeCompare(b.name)),
  },
  {
    name: 'Shrinking long strings',
    in: [
      'Donec lobortis eleifend condimentum. Cras dictum dolor lacinia lectus vehicula rutrum. Maecenas quis nisi nunc. Nam tristique feugiat est vitae mollis. Maecenas quis nisi nunc.',
      'Aliquam sollicitudin ante ligula, eget malesuada nibh efficitur et. Pellentesque massa sem, scelerisque sit amet odio id, cursus tempor urna. Etiam congue dignissim volutpat. Vestibulum pharetra libero et velit gravida euismod.',
      'Vestibulum pharetra libero et velit gravida euismod. Quisque mauris ligula, efficitur porttitor sodales ac, lacinia non ex. Fusce eu ultrices elit, vel posuere neque.',
    ],
  },
  {
    name: 'Shrinking arrays',
    // prettier-ignore
    in: [ 1235, 1235, 1235, 1235, 1235, 1235, 
        259874, 259874, 259874, 259874, 259874, 259874, 259874, 259874, 259874, 259874, 259874, 259874, 259874, 259874, 259874, 259874, 
        'academy', 'academy', 'academy', 'academy', 'academy', 'academy', 'academy', 'academy', 123, 'academy',
        true,true,true,true,true,true,true,
        false,false,false,false,false,false,
        null,null,null,null,null,null,
    ],
  },
]; //.filter((t) => t.name == 'players/id/tournaments');
